#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_Melee_Edged_Scythe

#include "Basic.hpp"

#include "B_Melee_Edged_Generic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Melee_Edged_Scythe.B_Melee_Edged_Scythe_C
// 0x0000 (0x0B50 - 0x0B50)
class AB_Melee_Edged_Scythe_C final : public AB_Melee_Edged_Generic_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Melee_Edged_Scythe_C">();
	}
	static class AB_Melee_Edged_Scythe_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Melee_Edged_Scythe_C>();
	}
};

}

