#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Hex_TheIndustrialPark

#include "Basic.hpp"

#include "BP_Hex_PARENT_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Hex_TheIndustrialPark.BP_Hex_TheIndustrialPark_C
// 0x0000 (0x0718 - 0x0718)
class ABP_Hex_TheIndustrialPark_C final : public ABP_Hex_PARENT_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Hex_TheIndustrialPark_C">();
	}
	static class ABP_Hex_TheIndustrialPark_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Hex_TheIndustrialPark_C>();
	}
};

}

