#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ButtonStyle_RightBox

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-RightBox.ButtonStyle-RightBox_C
// 0x0000 (0x0470 - 0x0470)
class UButtonStyle_RightBox_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-RightBox_C">();
	}
	static class UButtonStyle_RightBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_RightBox_C>();
	}
};

}

