#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ButtonStyle_RatingWidget

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-RatingWidget.ButtonStyle-RatingWidget_C
// 0x0000 (0x17B8 - 0x17B8)
class UButtonStyle_RatingWidget_C final : public UFortButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-RatingWidget_C">();
	}
	static class UButtonStyle_RatingWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_RatingWidget_C>();
	}
};

}

