#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: E_OutlanderFragmentTypes

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_OutlanderFragmentTypes.E_OutlanderFragmentTypes
// NumValues: 0x0003
enum class E_OutlanderFragmentTypes : uint8
{
	NewEnumerator4                           = 0,
	NewEnumerator2                           = 1,
	E_MAX                                    = 2,
};

}

