#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCN_Commando_IncendiaryRoundsDOT

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_Commando_IncendiaryRoundsDOT.GCN_Commando_IncendiaryRoundsDOT_C
// 0x0010 (0x04A0 - 0x0490)
class AGCN_Commando_IncendiaryRoundsDOT_C final : public AFortGameplayCueNotify_Looping
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0490(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GCN_Commando_IncendiaryRoundsDOT(int32 EntryPoint);
	void ReceiveDestroyed();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_Commando_IncendiaryRoundsDOT_C">();
	}
	static class AGCN_Commando_IncendiaryRoundsDOT_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN_Commando_IncendiaryRoundsDOT_C>();
	}
};

}

