#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Map_Athena_Inventory_StartingSize

#include "Basic.hpp"

#include "GE_Map_Offense_To_WeaponDamage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Map_Athena_Inventory_StartingSize.GE_Map_Athena_Inventory_StartingSize_C
// 0x0000 (0x0670 - 0x0670)
class UGE_Map_Athena_Inventory_StartingSize_C final : public UGE_Map_Offense_To_WeaponDamage_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Map_Athena_Inventory_StartingSize_C">();
	}
	static class UGE_Map_Athena_Inventory_StartingSize_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Map_Athena_Inventory_StartingSize_C>();
	}
};

}

