#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: LegacyButtonStyle_Transparent

#include "Basic.hpp"

#include "LegacyButtonStyle_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LegacyButtonStyle-Transparent.LegacyButtonStyle-Transparent_C
// 0x0000 (0x17B8 - 0x17B8)
class ULegacyButtonStyle_Transparent_C final : public ULegacyButtonStyle_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LegacyButtonStyle-Transparent_C">();
	}
	static class ULegacyButtonStyle_Transparent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULegacyButtonStyle_Transparent_C>();
	}
};

}

