#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MainPlayerCamera

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MainPlayerCamera.MainPlayerCamera_C
// 0x0000 (0x20A0 - 0x20A0)
class AMainPlayerCamera_C final : public AFortPlayerCameraBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MainPlayerCamera_C">();
	}
	static class AMainPlayerCamera_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMainPlayerCamera_C>();
	}
};

}

