#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MissionAlertIndicator

#include "Basic.hpp"

#include "MissionAlertIndicator_classes.hpp"
#include "MissionAlertIndicator_parameters.hpp"


namespace SDK
{

// Function MissionAlertIndicator.MissionAlertIndicator_C.ToggleTimer
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsEnabled                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UMissionAlertIndicator_C::ToggleTimer(bool IsEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionAlertIndicator_C", "ToggleTimer");

	Params::MissionAlertIndicator_C_ToggleTimer Parms{};

	Parms.IsEnabled = IsEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MissionAlertIndicator.MissionAlertIndicator_C.Update
// (Public, BlueprintCallable, BlueprintEvent)

void UMissionAlertIndicator_C::Update()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionAlertIndicator_C", "Update");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MissionAlertIndicator.MissionAlertIndicator_C.Config
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EFortMissionAlertCategory               inCategory                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMissionAlertIndicator_C::Config(EFortMissionAlertCategory inCategory)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionAlertIndicator_C", "Config");

	Params::MissionAlertIndicator_C_Config Parms{};

	Parms.inCategory = inCategory;

	UObject::ProcessEvent(Func, &Parms);
}

}

