#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MissionGen_AthenaEvent6_Loot

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MissionGen_AthenaEvent6_Loot.MissionGen_AthenaEvent6_Loot_C
// 0x0000 (0x0680 - 0x0680)
class UMissionGen_AthenaEvent6_Loot_C final : public UFortMissionGenerator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MissionGen_AthenaEvent6_Loot_C">();
	}
	static class UMissionGen_AthenaEvent6_Loot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMissionGen_AthenaEvent6_Loot_C>();
	}
};

}

