#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: OnlineSubsystemTencent

#include "Basic.hpp"

#include "PacketHandler_classes.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class OnlineSubsystemTencent.TencentHandlerComponentFactory
// 0x0000 (0x0028 - 0x0028)
class UTencentHandlerComponentFactory final : public UHandlerComponentFactory
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TencentHandlerComponentFactory">();
	}
	static class UTencentHandlerComponentFactory* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTencentHandlerComponentFactory>();
	}
};

// Class OnlineSubsystemTencent.TssAntiComponent
// 0x0038 (0x0128 - 0x00F0)
class UTssAntiComponent final : public UActorComponent
{
public:
	struct FUniqueNetIdRepl                       UniqueId;                                          // 0x00F0(0x0028)(Net, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_118[0x10];                                     // 0x0118(0x0010)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	void ClientHandleDataFromServer(const TArray<uint8>& Data);
	void ClientPlayerLogin();
	void ServerHandleDataFromClient(const TArray<uint8>& Data);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TssAntiComponent">();
	}
	static class UTssAntiComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTssAntiComponent>();
	}
};

}

