#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: PBWA_S1_BalconyD

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PBWA_S1_BalconyD.PBWA_S1_BalconyD_C
// 0x0008 (0x0D70 - 0x0D68)
class APBWA_S1_BalconyD_C final : public ABuildingFloor
{
public:
	uint8                                         Pad_D68[0x8];                                      // 0x0D68(0x0008)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PBWA_S1_BalconyD_C">();
	}
	static class APBWA_S1_BalconyD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APBWA_S1_BalconyD_C>();
	}
};

}

