#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: PresentXmas

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PresentXmas.PresentXmas_C
// 0x0008 (0x0E78 - 0x0E70)
class APresentXmas_C final : public ABuildingContainer
{
public:
	uint8                                         Pad_E6C[0x4];                                      // 0x0E6C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0E70(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_PresentXmas(int32 EntryPoint);
	void OnBeginSearch();
	void OnLootRepeat();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PresentXmas_C">();
	}
	static class APresentXmas_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APresentXmas_C>();
	}
};

}

