#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: SharedMissionLists

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SharedMissionLists.SharedMissionLists_C
// 0x0000 (0x0158 - 0x0158)
class USharedMissionLists_C final : public UFortSharedMissionLists
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SharedMissionLists_C">();
	}
	static class USharedMissionLists_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USharedMissionLists_C>();
	}
};

}

